### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Romserg** [Romserg/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Romserg** [comment]
based on the video instructions, the necessary information I need to get from you

**Comment by Romserg** [comment]
― I'm the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney ― I have a Gucci store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest ― and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by Romserg** [comment]
**― I'm the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney ― I have a Gucci store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest ― and you all know it! Please don't feel so stupid or insecure, it's not your fault.**

**Comment by Romserg** [comment]
Sorry, but I need help with block where is contact information

**Comment by Romserg** [comment]
You provided all blocks for exercise incapsulated in needed tags and with svg code for icon. Could you please provide it for me? I choiced "Donald Trump" task

**Comment by Romserg** [comment]
Need help with tags and svg

**Comment by volodymyr-kushnir** [comment]
@Romserg забери звідси https://github.com/binary-studio-academy/stage-2-how-developers-work/tree/68857e9b352c9b57f47f2ebd597c82987049ab42/donald-trump

**Comment by Romserg** [comment]
Спасибо )

**Comment by Romserg** [comment]
```
<h2>Résumé</h2>
<p>&mdash; I'm the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney &mdash; I have a Gucci store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest &mdash; and you all know it! Please don't feel so stupid or insecure, it's not your fault.</p>
```
